export const courses = [
  {
    id: 1,
    title: 'React Основи',
    category: 'Frontend',
    level: 'Начинаещ',
    rating: 4.8,
    students: 1200,
  },
  {
    id: 2,
    title: 'Node.js API',
    category: 'Backend',
    level: 'Среден',
    rating: 4.5,
    students: 880,
  },
  {
    id: 3,
    title: 'Docker и Kubernetes',
    category: 'DevOps',
    level: 'Напреднал',
    rating: 4.9,
    students: 460,
  },
  {
    id: 4,
    title: 'TypeScript в практика',
    category: 'Frontend',
    level: 'Среден',
    rating: 4.7,
    students: 730,
  },
  {
    id: 5,
    title: 'SQL и моделиране на данни',
    category: 'Backend',
    level: 'Начинаещ',
    rating: 4.4,
    students: 640,
  },
  {
    id: 6,
    title: 'CI/CD Pipelines',
    category: 'DevOps',
    level: 'Среден',
    rating: 4.6,
    students: 390,
  },
  {
    id: 7,
    title: 'UX за разработчици',
    category: 'Frontend',
    level: 'Начинаещ',
    rating: 4.3,
    students: 510,
  },
  {
    id: 8,
    title: 'Microservices Architecture',
    category: 'Backend',
    level: 'Напреднал',
    rating: 4.9,
    students: 280,
  },
]
